MobileWx.Web/Controllers/YwcxController.cs
using Sys.Controller;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Text;
using Sys.Utility;
using System.Data.SqlClient;
using MobileWx.Web.Models;
using System.Security.Cryptography;
using System.IO;

namespace MobileWx.Web.Controllers
{
    public class YwcxController : SysController
    {
        //

        private mobilewbs.mobilewbs wbs = new mobilewbs.mobilewbs();

        //业务查询首页
        public ActionResult Index()
        {
            return View();
        }

        //密码查询
        public ActionResult mscx()
        {
            return View();
        }

        //手机登录
        public ActionResult userLogin()
        {

            return View();
        }

        //PC登录
        public ActionResult userLoginPC()
        {

            return View();
        }

        //用户选择手机或PC
        public ActionResult userLoginPCorPhone()
        {

            return View();
        }

        //到期日查询
        public ActionResult dqr()
        {
            string cpnumber = string.Empty;
            if (Request.Cookies["userName"] != null)
            {
                cpnumber = Request.Cookies["userName"].Value;
            }

            if (string.IsNullOrEmpty(cpnumber))
            {
                Response.Cookies["pageType"].Value = "1";
                Response.Cookies["pageType"].Expires = DateTime.Now.AddHours(1);
                Response.Redirect("login");
            }
            else
            {
                @ViewBag.cpnumber = cpnumber;
                bind(cpnumber, "000000");
            }

            return View();
        }

        /// <summary>
        /// 验证手机号登录
        /// </summary>
        /// <param name="fc"></param>
        /// <returns></returns>
        public ActionResult Stock(FormCollection fc)
        {
            if (!string.IsNullOrEmpty(fc["action"].ToString()))
            {
                string name = fc["txt_name"].ToString();
                string pwd = fc["txt_pwd"].ToString();
                if (string.IsNullOrEmpty(name) || string.IsNullOrEmpty(pwd))
                {
                    Response.Write(String.Format("<script type='text/javascript'>alert('尊敬的用户，您好。手机号或密码不能为空，请从新填写！'); window.location.href='{0}';</script>", "login"));
                    Response.Write("<script>document.location=document.location;</script>");
                }
                else
                {
                    string returnStr = wbs.User_login_forweixin(name, pwd);
                    string[] arry = returnStr.Split('|');
                    string str = arry[0].ToString();
                    string str2 = arry[1].ToString();//0 是老用户，1是新用户
                    if (str == "1")
                    {

                        Response.Cookies["userName"].Value = name;
                        Response.Cookies["userName"].Expires = DateTime.Now.AddHours(1);


                        Response.Cookies["userType"].Value = str2;
                        Response.Cookies["userType"].Expires = DateTime.Now.AddHours(1);

                        string pageType = string.Empty;
                        if (Request.Cookies["pageType"] != null)
                        {
                            pageType = Request.Cookies["pageType"].Value;
                        }

                        if (pageType == "1")
                        {
                            Response.Redirect("dqr");
                        }
                        else if (pageType == "2")
                        {
                            Response.Redirect("jfdh");
                        }
                        else
                        {
                            Response.Redirect("recharge");
                        }

                    }
                    else
                    {
                        Response.Write(String.Format("<script type='text/javascript'>alert('尊敬的用户，您好。用户名或密码错误！'); window.location.href='{0}';</script>", "login"));
                        Response.Write("<script>document.location=document.location;</script>");
                    }
                }
            }
            return View();
        }


        /// <summary>
        /// 验证PC登录
        /// </summary>
        /// <param name="fc"></param>
        /// <returns></returns>
        public ActionResult StockPC(FormCollection fc)
        {
            if (!string.IsNullOrEmpty(fc["action"].ToString()))
            {
                string name = fc["txt_name"].ToString();
                string pwd = fc["txt_pwd"].ToString();
                if (string.IsNullOrEmpty(name) || string.IsNullOrEmpty(pwd))
                {
                    Response.Write(String.Format("<script type='text/javascript'>alert('尊敬的用户，您好。手机号或密码不能为空，请从新填写！'); window.location.href='{0}';</script>", "userLoginPC"));
                    Response.Write("<script>document.location=document.location;</script>");
                }
                else
                {

                    string cpnumber = string.Empty;
                    cpnumber = Request.Cookies["userName"].Value;
                    if (string.IsNullOrEmpty(cpnumber))
                    {
                        Response.Write(String.Format("<script type='text/javascript'>alert('尊敬的用户，您好。手机号或密码不能为空，请从新填写！'); window.location.href='{0}';</script>", "login"));
                        Response.Write("<script>document.location=document.location;</script>");
                    }
                    mobilePay.mobilePay mp = new mobilePay.mobilePay();
                    int str = mp.VerifyPCUser(cpnumber, name, pwd);
                    if (str >= 0)
                    {
                        //用户类型

                        Response.Cookies["userType"].Value = "2";//PC老用户
                        Response.Cookies["userType"].Expires = DateTime.Now.AddHours(1);
                    }
                    else
                    {
                        Response.Cookies["userType"].Value = "3";//PC验证过新用户
                        Response.Cookies["userType"].Expires = DateTime.Now.AddHours(1);
                    }
                    Response.Redirect("recharge");

                }
            }
            return View();
        }

        //积分兑换使用期产品列表
        public ActionResult jfdh()
        {
            string cpnumber = string.Empty;
            if (Request.Cookies["userName"] != null)
            {
                cpnumber = Request.Cookies["userName"].Value;
            }

            if (string.IsNullOrEmpty(cpnumber))
            {
                Response.Cookies["pageType"].Value = "2";
                Response.Cookies["pageType"].Expires = DateTime.Now.AddHours(1);
                Response.Redirect("login");
            }

            mobilewbs.mobilewbs ws = new mobilewbs.mobilewbs();
            string retStr = ws.sp_qry_mobile_loyalty_points_weixin(cpnumber);
            string[] arry = retStr.Split('|');
            ViewBag.jifen = arry[0];

            DataSet ds = new DataSet();
            ds = Get_productList();

            if (ds.Tables[0].Rows.Count > 0)
            {
                StringBuilder build = new StringBuilder();

                for (int i = 0; i < ds.Tables[0].Rows.Count; i++)
                {
                    build.Append(" <tr><td id=\"td-item\"><div id=\"div-item\"><img width=\"88px\" height=\"57px\" alt=\"img\" src=\"../Css/def/images/");
                    build.Append((i + 1).ToString());
                    build.Append(".png\"><div><span class=\"content content-title\">");
                    build.Append(ds.Tables[0].Rows[i]["cardName"].ToString());
                    build.Append("</span><span class=\"content content-point\">");
                    build.Append(ds.Tables[0].Rows[i]["needIntegral"].ToString());
                    build.Append("积分</span><span class=\"content content-remain\">剩余数量:");
                    build.Append(ds.Tables[0].Rows[i]["surplus"].ToString());
                    build.Append("  </span></div><a href=\"jfdh2?type=" + ds.Tables[0].Rows[i]["cardType"].ToString() + "\" class=\"item-button ui-link\" id=\"item-button\" rowindex=\"1\">兑换 </a></div></td></tr>");

                }
                ViewBag.quote = Convert.ToString(build);
            }
            return View();
        }

        /// <summary>
        /// 积分兑换使用期
        /// </summary>
        /// <returns></returns>
        public ActionResult jfdh2()
        {
            string cpnumber = string.Empty;
            if (Request.Cookies["userName"] != null)
            {
                cpnumber = Request.Cookies["userName"].Value;
            }

            if (string.IsNullOrEmpty(cpnumber))
            {
                Response.Cookies["pageType"].Value = "2";
                Response.Cookies["pageType"].Expires = DateTime.Now.AddHours(1);
                Response.Write(String.Format("<script type='text/javascript'>alert('尊敬的用户，您好。请先登录再查询！'); window.location.href='{0}';</script>", "login"));
                Response.Write("<script>document.location=document.location;</script>");

            }
            else
            {

                string query = Request.QueryString["type"].ToString();
                if (string.IsNullOrEmpty(query) == false)
                {
                    int integral = 0;
                    switch (query)
                    {
                        case "1":
                            integral = 2;
                            break;
                        case "2":
                            integral = 6;
                            break;
                        case "3":
                            integral = 12;
                            break;
                        case "4":
                            integral = 24;
                            break;
                        default:
                            integral = 0;
                            break;

MobileWx.Web/Views/Ywcx/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1,initial-scale=1, minimum-scale=1.0, maximum-scale=1.0,user-scalable=no" /> 
   
</head>
<body>
    <div class="bd">
        <div>
            <h5>OAuth2网页授权测试</h5>
        </div> 
        <div class="index_bottom"> 
        </div>
    </div>
</body>
</html>

MobileWx.Web/Views/Ywcx/buy.cshtml
@{
    ViewBag.Title = "支付选择";
    ViewBag.css = @Url.Content("~/Css/def/em.wx.css");
    ViewBag.css2 = @Url.Content("~/Css/def/login2.css");
    Layout = "~/Views/Shared/_LayoutYwcx.cshtml";
}


<style type="text/css">
    #popwin .pwinset p {
        margin-top: 20px;
        line-height: 28px;
    }

    #popwin .pwinset .ln {
        height: 52px;
        width: 80%;
        border: none;
        line-height: 52px;
        text-align: center;
    }


    #popwin {
        background-color: rgb(244,241,238);
    }

    #img1, #img2 {
        margin: 0;
        padding: 0;
        margin-left: 20px;
        border: none;
        width: 100%;
    }

    #ps {
        font-size: large;
        font-weight: bold;
    }

    a:link {
        color: black;
        text-decoration: none;
    }

    a:active {
        color: black;
    }

    a:visited {
        color: black;
        text-decoration: none;
    }

    a:hover {
        color: black;
        text-decoration: none;
    }
</style>

<body id="login_body">

    <div class="rgba_back">
    </div>
    <div id="login">

        <div class="popwin" id="popwin">
            <div class="pwinset">
                <p id="ps">
                    请选择支付方式：
                </p>
                <section>
                    <div class="ln">
                        @Html.Raw(@ViewBag.zhifu)
                        <img id="img1" src="../Css/def/images/zhifu.png" /></a>
                    </div>
                </section>
                <section>
                    <div class="ln">
                        @Html.Raw(@ViewBag.cft)
                        <img id="img2" src="../Css/def/images/caifu.png" /></a>
                    </div>
                </section>
                <div class="close" onclick=" location.assign('recharge');">×</div>
            </div>
        </div>

    </div>
</body>

MobileWx.Web/Views/Ywcx/jf.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="viewport" content="width=device-width, initial-scale=1,initial-scale=1, minimum-scale=1.0, maximum-scale=1.0,user-scalable=no" />
    <link href="@Url.Content("~/Css/def/style_new.css")"   rel="stylesheet" type="text/css" />
    <title>积分服务</title>
</head>
<body>
    <div class="main">
        <p class="p_1">积分服务</p>
        <p class="p_2">@ViewBag.quote </p>
        <p class="p_3">
            <img src="../Css/def/images/jf.png" />
        </p>
        <p class="p_4">积分查询和兑换</p>
        <p class="p_5"></p>
        <div class="div_6">
            <a href="@Url.Content("~/Ywcx/jfdh")">
                <ul>
                    <li class="first">阅读全文</li>
                    <li>
                        <img src="../Css/def/images/gd.png" /></li>
                </ul>
            </a>
        </div>
    </div>
</body>
</html>

MobileWx.Web/Views/Ywcx/jfdh2.cshtml
@{
    ViewBag.Title = "积分兑换";
    ViewBag.css = @Url.Content("~/Css/def/em.wx.css");
    Layout = "~/Views/Shared/_LayoutYwcx.cshtml";
}

<body>
    <div class="jffw_div">
        <img src="../Css/def/images/jifen.png" />
    </div>
    <div>
        @Html.Raw(@ViewBag.quote)
    </div>
</body>

MobileWx.Web/Views/Ywcx/login.cshtml
@{
    ViewBag.Title = "到期日查询";
    ViewBag.css = @Url.Content("~/Css/def/style_new.css");
    Layout = "~/Views/Shared/_LayoutYwcx.cshtml";
}

<script type="text/javascript">

    function clearText(field) {

        if (field.defaultValue == field.value) {
            field.value = '';
        }
        else if (field.value == '') {
            field.value = field.defaultValue;
        }

    }

    function clearText2(field) {
        if (field.defaultValue == '') {
            document.getElementById("mima").style.background = "url(images/white.png)";
        }
        else if (field.value == field.value) {
            document.getElementById("mima").style.background = "url(images/mima.png)";
        }
    }


    function psw(el) {
        if (el.value == '请输入密码') {
            el.value = '';
            el.type = 'password';
        }
    }
    function txt(el) {
        if (!el.value) {
            el.type = 'text';
            el.value = '请输入密码';
        }
    }

</script>



<body>
    <div class="login">
        <div class="detail">
            请先登录您的操盘手账号
        </div>
        @using (Html.BeginForm("Stock", "Ywcx", FormMethod.Post))
        {
            <div>
                <input id="phone" type="text" value="请输入手机号" class="txt" name="txt_name" maxlength="11" onfocus="clearText(this)" onblur="clearText(this)" />

            </div>           

            <div>
                <input id="mima" type="text" value="请输入密码" class="txt2" name="txt_pwd" maxlength="6" onfocus="psw(this)" onblur="txt(this) " />

            </div>
            <p class="lg_rt">
                <a href="sms:106909990909" target="_blank">立即注册</a>&nbsp;&nbsp;<a href="sms:106695887109" target="_blank">忘记密码</a>

            </p>
            <div class="check">
                <input type="submit" value="登 录" name="action" class="btn" />
            </div>
        }
    </div>
</body>

MobileWx.Web/Views/Ywcx/recharge.cshtml
@{
    ViewBag.Title = "充值";
    ViewBag.css = @Url.Content("~/Css/def/em.wx.css");
    ViewBag.css2 = @Url.Content("~/Css/def/mobcss.css");

    ViewBag.js = @Url.Content("~/Js/jquery.min.js");
    //ViewBag.js2 = @Url.Content("~/Js/recharge.js");
    Layout = "~/Views/Shared/_LayoutYwcx.cshtml";
}

<script type="text/javascript">
    $(document).ready(function () {

        $(".header li").click(function () {
            $(".header li").css("color", "black");
            var indexId = $(this).index();
            if (indexId != 0) {
                $("#img4").attr("src", "../Css/def/images/cz_header_" + indexId + ".png");
            }

            if (indexId == 0) {
            }
            else if (indexId == 1) {
                $(".header #li_1").css("color", "white");
                $(".header #li_1").css("background", "url(../Css/def/images/cz_01.png)");
                $(".header #li_2").css("background", "url(../Css/def/images/cz_022.png)");
                $(".header #li_3").css("background", "url(../Css/def/images/cz_033.png)");
                addCSS();
            }
            else if (indexId == 2) {

                $(".header #li_2").css("color", "white");
                $(".header #li_2").css("background", "url(../Css/def/images/cz_02.png)");
                $(".header #li_1").css("background", "url(../Css/def/images/cz_011.png)");
                $(".header #li_3").css("background", "url(../Css/def/images/cz_033.png)");
                addCSS();




            }
            else {
                $(".header #li_3").css("color", "white");
                $(".header #li_3").css("background", "url(../Css/def/images/cz_03.png)");
                $(".header #li_2").css("background", "url(../Css/def/images/cz_022.png)");
                $(".header #li_1").css("background", "url(../Css/def/images/cz_011.png)");
                addCSS();

            }

        });


        function addCSS() {
            $(".header #li_1").css("background-position-x", "center");
            $(".header #li_1").css("background-position-y", "top");
            $(".header #li_1").css("background-repeat", "no-repeat");
            $(".header #li_1").css("background-size", "60px");
            $(".header #li_2").css("background-position-x", "center");
            $(".header #li_2").css("background-position-y", "top");
            $(".header #li_2").css("background-repeat", "no-repeat");
            $(".header #li_2").css("background-size", "60px");
            $(".header #li_3").css("background-position-x", "center");
            $(".header #li_3").css("background-position-y", "top");
            $(".header #li_3").css("background-repeat", "no-repeat");
            $(".header #li_3").css("background-size", "60px");
        }


    }
)</script>



<body id="bg">
    <div class="top">
        特色介绍
     
    </div>

    <div class="raised">

        <div class="header">
            <ul>
                <li>
                    <p>
                        手机<br />
                        主力版
                    </p>
                </li>
                <li id="li_1">判大势
                </li>
                <li id="li_2">选好股
                </li>
                <li id="li_3">稳操作
                </li>
            </ul>
        </div>


        <div class="detail">
            <br />
            <img id="img4" src="../Css/def/images/cz_header_1.png" />
        </div>
        <br />


    </div>

    <div class="product">
        产品选择
    </div>

    <div class="raisedDown">

        <section class="ProList">
            <dl>
                <dt><span class="titpro">
                    @Html.Raw(@ViewBag.listStr)
                </span><span class="morepro"><a id="showMorepro">更多产品
                    <img src="@Url.Content("~/Css/def/images/parrow.png")" class="parrow" alt="" /></a></span></dt>
                <dd id="showProList">
                    <ul>
                        @Html.Raw(@ViewBag.listStr2)
                    </ul>
                    <div class="clr"></div>
                </dd>
            </dl>
        </section>


    </div>
    <br />
    <br />
    <script>
        var proItem = $(".ProList dl .proitem");
        proItem.mouseover(function () {
            proItem.removeClass("sel");
            $(this).toggleClass("sel");

        });
        $("#showMorepro").click(function () {
            $(this).toggleClass("sel");
            $("#showProList").toggle();

            if ($(this).hasClass("sel")) {
                $("img", this).attr("src", "@Url.Content("~/Css/def/images/parrow0.png")");
            } else {
                $("img", this).attr("src", "@Url.Content("~/Css/def/images/parrow.png")");
            }
        });

    </script>
</body>

MobileWx.Web/Views/Ywcx/rx.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="viewport" content="width=device-width, initial-scale=1,initial-scale=1, minimum-scale=1.0, maximum-scale=1.0,user-scalable=no" />
    <link href="@Url.Content("~/Css/def/style_new.css")"   rel="stylesheet" type="text/css" />
    <title>软件下载</title>
</head>
<body>
    <div class="main">
        <p class="p_1">软件下载</p>
        <p class="p_2">@ViewBag.quote </p>
        <p class="p_3">
            <img src="../Css/def/images/rx.png" />
        </p>
        <p class="p_4">
            手机登录&nbsp;&nbsp;wap.emoney.cn
           
        </p>
        <p class="p_5"></p>
        <div class="div_6">
            <a href="http://wap.emoney.cn">
                <ul>
                    <li class="first">阅读全文</li>
                    <li>

                        <img src="../Css/def/images/gd.png" /></li>
                </ul>
            </a>
        </div>
    </div>
</body>
</html>

MobileWx.Web/Views/Ywcx/szjq.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="viewport" content="width=device-width, initial-scale=1,initial-scale=1, minimum-scale=1.0, maximum-scale=1.0,user-scalable=no" />
    <link href="@Url.Content("~/Css/def/style_new.css")"   rel="stylesheet" type="text/css" />
    <title>实战技巧</title>

</head>
<body>
    <a href="@Url.Content("~/html/szjq_1_1.html")">
        <div class="main">
            <p class="p_1">实战技巧:经典战法应对万变行情</p>
            <p class="p_2">@ViewBag.quote </p>
            <p class="p_ts">
                <img src="../Css/def/images/szjq.png" />
            </p>
            <p class="p_4">累计益盟研究团队多年炒股经验，而练就的经典战法，结合软件功能操作，简单易学，有效。</p>
            <p class="p_5"></p>
            <div class="div_6">

                <ul>
                    <li class="first">阅读全文</li>
                    <li>
                        <img src="../Css/def/images/gd.png" /></li>
                </ul>

            </div>
        </div>
    </a>
</body>
</html>

MobileWx.Web/Views/Ywcx/userLogin.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, maximum-scale=1.0,user-scalable=no" />
    <link href="@Url.Content("~/Css/def/em.wx.css")"   rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Css/def/login.css")"   rel="stylesheet" type="text/css" />
    <title>软件登录</title>
 

</head>
<body>
    <div>
        <table class="ywcx">
            <tr>
                <td class="td_first">
                    <a href="#"></a>

                </td>
                <td class="td_second">
                    <a href="#"></a>

                </td>
                <td class="td_third">
                    <a href="#"></a>
                </td>
            </tr>
            <tr>
                <td class="td_30">密码查询</td>
                <td class="td_30">到期日查询</td>
                <td class="td_30">积分服务</td>
            </tr>
            <tr>
                <td class="td4">
                    <a href="#"></a>
                </td>
                <td class="td5">
                    <a href="#"></a>
                </td>
                <td class="td6">
                    <a href="#"></a>
                </td>
            </tr>
            <tr>
                <td class="td_30">购买充值</td>
                <td class="td_30">我要优惠</td>
                <td class="td_30">软件下载</td>
            </tr>
        </table>
    </div>
    <div id="login">
        @using (Html.BeginForm("Stock", "Ywcx", FormMethod.Post))
        {
            
            <div class="popwin" id="popwin">
                <div class="pwinset">
                    <header>用户登录</header>
                    <section>
                        <div class="ln">
                            <label>请输入手机号码：</label><input type="text" onclick="close()" class="inp" name="txt_name" id="textfield" maxlength="11" />
                        </div>
                        <div class="ln" style="border-top: none;">
                            <label>请输密码：</label><input type="password" class="inp" name="txt_pwd" id="textfield" maxlength="6" />
                        </div>
                    </section>
                    <section>
                        <div class="tijiao">
                            <ul>
                                <li>
                                    <input type="submit" value="确定" name="action" class="btn" /></li>
                                <li>

                                    <input id="Button1" type="button" value="注册" class="btn" onclick=" location.assign('Index');" />
                                </li>
                            </ul>
                        </div>

                    </section>
                    <div class="close" onclick=" location.assign('Index');">×</div>
                </div>
            </div>
        }
        @*        <script src="@Url.Content("~/js/bq.js")"></script>*@
        <div class="index_bottom">
            益盟操盘手 创建于2002年<br />
            2013 益盟操盘手 版权所有<br />
            ICP许可证号 沪ICP备06000340
        </div>
        <br />
    </div>
</body>
</html>

MobileWx.Web/Views/Ywcx/userLoginPC.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="viewport" content="width=device-width,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
    <link href="@Url.Content("~/Css/def/style_new.css")"   rel="stylesheet" type="text/css" />
    <title>EM/RTX号验证</title>
    <script type="text/javascript">

        function clearText(field) {
            if (field.defaultValue == field.value) {
                field.value = '';

            }
            else if (field.value == '') {
                field.value = field.defaultValue;
            }
        }



        function psw(el) {
            if (el.value == '请输入密码') {
                el.value = '';
                el.type = 'password';
            }
        }
        function txt(el) {
            if (!el.value) {
                el.type = 'text';
                el.value = '请输入密码';
            }
        }
        function clearText2(field) {
            var val = document.getElementById("mima").value;

            if (field.defaultValue == '') {
                document.getElementById("mima").style.background = "url(images/white.png)";
            }
            else if (field.value == field.value) {
                document.getElementById("mima").style.background = "url(images/mima.png)";
            }
        }
    </script>
</head>
<body>
    <div class="login">
        <div class="detail">
            请先登录您的操盘手账号
        </div>
        @using (Html.BeginForm("StockPC", "Ywcx", FormMethod.Post))
        {
            <div>
                <input type="text" value="请输入EM/RTX号" class="txt" name="txt_name" maxlength="11" onfocus="clearText(this)" onblur="clearText(this)" />

            </div>           

            <div>
                <input id="mima" type="text" value="请输入密码" class="txt2" name="txt_pwd" maxlength="6" onfocus="psw(this)" onblur="txt(this) " />

            </div>
            <p class="lg_rt">
                <a href="sms:106909990909">立即注册</a>&nbsp;&nbsp;<a href="sms:106695887109">忘记密码</a>

            </p>
            <div class="check">
                <center><input type="submit" value="登 录" name="action" class="btn" /></center>
            </div>
        }
    </div>
</body>
</html>

MobileWx.Web/Views/Ywcx/副本 userLoginPC.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, maximum-scale=1.0,user-scalable=no" />
    <link href="@Url.Content("~/Css/def/em.wx.css")"   rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Css/def/login.css")"   rel="stylesheet" type="text/css" />
    <title>软件登录</title>
    <style type="text/css">
        .tijiao li {
            width: 100%;
        }

        #popwin label {
            text-align: center;
            width: 75px;
        }

        #popwin p {
            margin-top: 20px;
            margin-left: 20px;
            margin-right: 20px;
        }
    </style>
</head>
<body>
    <div>
        <table class="ywcx">
            <tr>
                <td class="td_first">
                    <a href="#"></a>

                </td>
                <td class="td_second">
                    <a href="#"></a>

                </td>
                <td class="td_third">
                    <a href="#"></a>
                </td>
            </tr>
            <tr>
                <td class="td_30">密码查询</td>
                <td class="td_30">到期日查询</td>
                <td class="td_30">积分服务</td>
            </tr>
            <tr>
                <td class="td4">
                    <a href="#"></a>
                </td>
                <td class="td5">
                    <a href="#"></a>
                </td>
                <td class="td6">
                    <a href="#"></a>
                </td>
            </tr>
            <tr>
                <td class="td_30">购买充值</td>
                <td class="td_30">我要优惠</td>
                <td class="td_30">软件下载</td>
            </tr>
        </table>
    </div>
    <div id="login">
        @using (Html.BeginForm("StockPC", "Ywcx", FormMethod.Post))
        {
            
            <div class="popwin" id="popwin">
                <div class="pwinset">
                    <p>
                        请输入您的电脑版账号与密码，才可以享受购买优惠！

                    </p>
                    <section>
                        <div class="ln">
                            <label>EMFXT号：</label><input type="text" onclick="close()" class="inp" name="txt_name" id="textfield" maxlength="11" />
                        </div>
                        <div class="ln" style="border-top: none;">
                            <label>产品密码：</label><input type="password" class="inp" name="txt_pwd" id="Password1" maxlength="6" />
                        </div>
                    </section>
                    <section>
                        <div class="tijiao">
                            <ul>
                                <li>
                                    <input type="submit" value="登录" name="action" class="btn" /></li>

                            </ul>
                        </div>

                    </section>
                    <div class="close" onclick=" location.assign('Index');">×</div>
                </div>
            </div>
        }
        <div class="index_bottom">
            益盟操盘手 创建于2002年<br />
            2013 益盟操盘手 版权所有<br />
            ICP许可证号 沪ICP备06000340
        </div>
        <br />
    </div>
</body>
</html>